In [1]:
import pandas as pd

In [53]:
df = pd.read_csv('data_extraction.csv')

In [35]:
df.columns

Index(['Company', 'Year', 'Total Revenue', 'Net Income', 'Total Assets',
       'Total Liabilities', 'Cash Flow from Operating Activities',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15'],
      dtype='str')

In [55]:
df['Total Revenue'] = pd.to_numeric(df['Total Revenue'], errors='coerce') #changing total revenue to float

In [56]:
df['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change() * 100

In [57]:
df['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100

In [59]:
df['Revenue Growth (%)'] = df.groupby('Company')['Total Revenue'].pct_change() * 100

df['Net Income Growth (%)'] = df.groupby('Company')['Net Income'].pct_change() * 100

df['Assets Growth (%)'] = df.groupby('Company')['Total Assets'].pct_change() * 100

df['Liabilities Growth (%)'] = df.groupby('Company')['Total Liabilities'].pct_change() * 100

df['Operating Cash Flow Growth (%)'] = df.groupby('Company')['Cash Flow from Operating Activities'].pct_change() * 100

In [60]:
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Operating Cash Flow Growth (%)
0,Microsoft,2023,211915,72361,411976,205753,87582,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2024,245122,88136,512163,243686,118548,15.669962,21.800417,24.318650,18.436183,35.356580
2,Microsoft,2025,281724,101832,619003,275524,136162,14.932156,15.539621,20.860546,13.065174,14.858117
3,Tesla,2023,96773,14974,106618,43009,13256,NaN,NaN,NaN,NaN,NaN
4,Tesla,2024,97690,7153,122070,48390,14923,0.947578,-52.230533,14.492862,12.511335,12.575438
5,Tesla,2025,94827,3855,137806,54941,14747,-2.930699,-46.106529,12.890964,13.537921,-1.179388
6,Apple,2023,383285,96995,353583,290437,110543,NaN,NaN,NaN,NaN,NaN
7,Apple,2024,391035,93736,364980,308030,118254,2.021994,-3.359967,3.223288,6.057424,6.975566
8,Apple,2025,416161,112010,359241,285508,111482,6.425512,19.495178,-1.572415,-7.311625,-5.726656

In [68]:
df.groupby('Company')[[
    'Total Revenue',
    'Net Income',
    'Total Assets',
    'Total Liabilities',
    'Cash Flow from Operating Activities'
]].mean() #average of each company

,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities
Company,,,,,
Apple,396827.000000,100913.666667,359268.000000,294658.333333,113426.333333
Microsoft,246253.666667,87443.000000,514380.666667,241654.333333,114097.333333
Tesla,96430.000000,8660.666667,122164.666667,48780.000000,14308.666667

In [71]:
df.groupby('Company')[[
    'Total Revenue',
    'Net Income',
    'Total Assets',
    'Total Liabilities',
    'Cash Flow from Operating Activities'
]].max() #maximum value of company

,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities
Company,,,,,
Apple,416161,112010,364980,308030,118254
Microsoft,281724,101832,619003,275524,136162
Tesla,97690,14974,137806,54941,14923

In [72]:
df.groupby('Company')[[
    'Total Revenue',
    'Net Income',
    'Total Assets',
    'Total Liabilities',
    'Cash Flow from Operating Activities'
]].min() #minimum value of company

,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities
Company,,,,,
Apple,383285,93736,353583,285508,110543
Microsoft,211915,72361,411976,205753,87582
Tesla,94827,3855,106618,43009,13256

In [73]:
df.groupby('Year')[[
    'Total Revenue',
    'Net Income',
    'Total Assets',
    'Total Liabilities',
    'Cash Flow from Operating Activities'
]].mean() #average of each year

,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities
Year,,,,,
2023,230657.666667,61443.333333,290725.666667,179733.000000,70460.333333
2024,244615.666667,63008.333333,333071.000000,200035.333333,83908.333333
2025,264237.333333,72565.666667,372016.666667,205324.333333,87463.666667

In [74]:
df.groupby('Year')[[
    'Total Revenue',
    'Net Income',
    'Total Assets',
    'Total Liabilities',
    'Cash Flow from Operating Activities'
]].min() #minimum value of year

,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities
Year,,,,,
2023,96773,14974,106618,43009,13256
2024,97690,7153,122070,48390,14923
2025,94827,3855,137806,54941,14747

In [75]:
df.groupby('Year')[[
    'Total Revenue',
    'Net Income',
    'Total Assets',
    'Total Liabilities',
    'Cash Flow from Operating Activities'
]].max() #maximum value of year

,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities
Year,,,,,
2023,383285,96995,411976,290437,110543
2024,391035,93736,512163,308030,118548
2025,416161,112010,619003,285508,136162

In [77]:
df.groupby('Company')['Total Revenue'].max() #max revenue by company

Company
Apple        416161
Microsoft    281724
Tesla         97690
Name: Total Revenue, dtype: int64

In [78]:
df.groupby('Company')['Total Revenue'].min() #min revenue by company

Company
Apple        383285
Microsoft    211915
Tesla         94827
Name: Total Revenue, dtype: int64

## Summary of Findings

The analysis of Microsoft, Apple, and Tesla's financial data from 2023 to 2025 shows differences in their financial performance and growth patterns.

Apple recorded the highest average revenue among the three companies during the period, while Microsoft also maintained a strong level of revenue. Tesla's revenue was lower in comparison, but the company experienced notable changes in its financial metrics over the three-year period.

The year-over-year analysis shows that revenue and net income changed differently across the three companies. These changes indicate that each company experienced different levels of growth and financial performance between 2023 and 2025. Tesla actually had a decrease in total revenue by 2% from 2024 to 2025, also having a a significant decrease in income over this same period.

The analysis of total assets and liabilities also provides insight into the financial position of each company. Changes in these metrics may indicate differences in how the companies expanded their operations and managed their financial obligations.

Operating cash flow provides an additional measure of financial performance because it shows the cash generated from normal business operations. Comparing operating cash flow across the companies helps identify which companies generated stronger cash flows from their core activities. With each company experiencing a decrease in Cash Flow from Operating Activities over the 3 years. 

Overall, the analysis demonstrates that Microsoft, Apple, and Tesla had different financial trends between 2023 and 2025. The combination of year-over-year growth rates and aggregate statistics provides a clearer view of their financial performance over the period.

## Methodology

The financial data for Microsoft, Apple, and Tesla was collected from their 10-K filings for the years 2023 to 2025. The data includes Total Revenue, Net Income, Total Assets, Total Liabilities, and Cash Flow from Operating Activities.

The data was organized in a CSV file and imported into Python using pandas. Year-over-year percentage changes were calculated for each financial metric to identify changes in financial performance over time. The `groupby()` function and aggregate functions such as `mean()`, `max()`, and `min()` were also used to compare financial performance across companies and years.

In [81]:
from IPython.display import FileLink

df.to_csv('financial_analysis.csv', index=False)
FileLink('financial_analysis.csv')

/Users/Apple/Documents/Job Simulations/Data Scientist Gen AI/Project Jupyter Notebook/financial_analysis.csv

# Task 2: GenAI Chatbot Prototype

## Step 1: Preparation

The financial data analyzed in Task 1 will be used as the data source for the chatbot. The chatbot will provide responses to predefined financial queries based on the financial information for Microsoft, Apple, and Tesla from 2023 to 2025.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('financial_analysis.csv')

In [26]:
df.head() #prints only first 5 rows

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Operating Cash Flow Growth (%)
0,Microsoft,2023,211915,72361,411976,205753,87582,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2024,245122,88136,512163,243686,118548,15.669962,21.800417,24.318650,18.436183,35.356580
2,Microsoft,2025,281724,101832,619003,275524,136162,14.932156,15.539621,20.860546,13.065174,14.858117
3,Tesla,2023,96773,14974,106618,43009,13256,NaN,NaN,NaN,NaN,NaN
4,Tesla,2024,97690,7153,122070,48390,14923,0.947578,-52.230533,14.492862,12.511335,12.575438

In [27]:
df #prints entire document

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Liabilities Growth (%),Operating Cash Flow Growth (%)
0,Microsoft,2023,211915,72361,411976,205753,87582,NaN,NaN,NaN,NaN,NaN
1,Microsoft,2024,245122,88136,512163,243686,118548,15.669962,21.800417,24.318650,18.436183,35.356580
2,Microsoft,2025,281724,101832,619003,275524,136162,14.932156,15.539621,20.860546,13.065174,14.858117
3,Tesla,2023,96773,14974,106618,43009,13256,NaN,NaN,NaN,NaN,NaN
4,Tesla,2024,97690,7153,122070,48390,14923,0.947578,-52.230533,14.492862,12.511335,12.575438
5,Tesla,2025,94827,3855,137806,54941,14747,-2.930699,-46.106529,12.890964,13.537921,-1.179388
6,Apple,2023,383285,96995,353583,290437,110543,NaN,NaN,NaN,NaN,NaN
7,Apple,2024,391035,93736,364980,308030,118254,2.021994,-3.359967,3.223288,6.057424,6.975566
8,Apple,2025,416161,112010,359241,285508,111482,6.425512,19.495178,-1.572415,-7.311625,-5.726656

In [28]:
df.shape #To know number of rows and columns available

(9, 12)

## Step 2: Chatbot Design and Data Preparation

### Predefined Queries

The chatbot will be designed to respond to the following predefined financial queries:

1. What was the total revenue for a company in 2025?
2. What was the net income for a company in 2025?
3. How did revenue change from 2024 to 2025?
4. How did net income change from 2024 to 2025?
5. What was the average revenue for each company from 2023 to 2025?

In [7]:
apple_2025 = df[
    (df['Company'] == 'Apple') &
    (df['Year'] == 2025)
]['Total Revenue'].iloc[0]

print(f"Apple's total revenue in 2025 was {apple_2025:,.0f}.") #Trying to get data from the csv dataframe and not instead hardcoding it

Apple's total revenue in 2025 was 416,161.

In [23]:
#creating responses for all three companies. Query 1: Total Revenue
for company in ['Microsoft', 'Apple', 'Tesla']:
    revenue = df[
        (df['Company'] == company) &
        (df['Year'] == 2025)
    ]['Total Revenue'].iloc[0]

    print(f"{company}'s total revenue in 2025 was {revenue:,.0f}.")

Microsoft's total revenue in 2025 was 281,724.
Apple's total revenue in 2025 was 416,161.
Tesla's total revenue in 2025 was 94,827.

In [13]:
#creating a dictionary that maps questions → responses.
responses = {
    "What was Apple's revenue in 2025?":
        "Apple's total revenue in 2025 was 416,161.",

    "What was Microsoft's revenue in 2025?":
        "Microsoft's total revenue in 2025 was 281,724.",

    "What was Tesla's revenue in 2025?":
        "Tesla's total revenue in 2025 was 97,690."
}

In [22]:
#creating responses for all three companies. Query 2: Net income
for company in ['Microsoft', 'Apple', 'Tesla']:
    net_income = df[
        (df['Company'] == company) &
        (df['Year'] == 2025)
    ]['Net Income'].iloc[0]

    print(f"{company}'s net income in 2025 was {net_income:,.0f}.")

Microsoft's net income in 2025 was 101,832.
Apple's net income in 2025 was 112,010.
Tesla's net income in 2025 was 3,855.

In [15]:
for company in ['Microsoft', 'Apple', 'Tesla']:
    net_income = df[
        (df['Company'] == company) &
        (df['Year'] == 2025)
    ]['Net Income'].iloc[0]

    responses[f"What was {company}'s net income in 2025?"] = (
        f"{company}'s net income in 2025 was {net_income:,.0f}."
    )

In [18]:
responses #checking responses and queries

{"What was Apple's revenue in 2025?": "Apple's total revenue in 2025 was 416,161.",
 "What was Microsoft's revenue in 2025?": "Microsoft's total revenue in 2025 was 281,724.",
 "What was Tesla's revenue in 2025?": "Tesla's total revenue in 2025 was 97,690.",
 "What was Microsoft's net income in 2025?": "Microsoft's net income in 2025 was 101,832.",
 "What was Apple's net income in 2025?": "Apple's net income in 2025 was 112,010.",
 "What was Tesla's net income in 2025?": "Tesla's net income in 2025 was 3,855."}

In [21]:
#retrieving revenue change for all three companies.
for company in ['Microsoft', 'Apple', 'Tesla']:
    revenue_growth = df[
        (df['Company'] == company) &
        (df['Year'] == 2025)
    ]['Revenue Growth (%)'].iloc[0]

    print(
        f"{company}'s revenue changed by "
        f"{revenue_growth:.2f}% from 2024 to 2025."
    )

Microsoft's revenue changed by 14.93% from 2024 to 2025.
Apple's revenue changed by 6.43% from 2024 to 2025.
Tesla's revenue changed by -2.93% from 2024 to 2025.

In [29]:
#creating Query 3 and adding to responses: Revenue change from 2024 to 2025.
for company in ['Microsoft', 'Apple', 'Tesla']:
    revenue_growth = df[
        (df['Company'] == company) &
        (df['Year'] == 2025)
    ]['Revenue Growth (%)'].iloc[0]

    responses[f"How did {company}'s revenue change from 2024 to 2025?"] = (
        f"{company}'s revenue changed by {revenue_growth:.2f}% "
        f"from 2024 to 2025."
    )

In [30]:
responses #checking responses and queries

{"What was Apple's revenue in 2025?": "Apple's total revenue in 2025 was 416,161.",
 "What was Microsoft's revenue in 2025?": "Microsoft's total revenue in 2025 was 281,724.",
 "What was Tesla's revenue in 2025?": "Tesla's total revenue in 2025 was 97,690.",
 "What was Microsoft's net income in 2025?": "Microsoft's net income in 2025 was 101,832.",
 "What was Apple's net income in 2025?": "Apple's net income in 2025 was 112,010.",
 "What was Tesla's net income in 2025?": "Tesla's net income in 2025 was 3,855.",
 "How did Microsoft's revenue change from 2024 to 2025?": "Microsoft's revenue changed by 14.93% from 2024 to 2025.",
 "How did Apple's revenue change from 2024 to 2025?": "Apple's revenue changed by 6.43% from 2024 to 2025.",
 "How did Tesla's revenue change from 2024 to 2025?": "Tesla's revenue changed by -2.93% from 2024 to 2025."}

In [31]:
#retrieving net income change for all three companies.
for company in ['Microsoft', 'Apple', 'Tesla']:
    net_income_growth = df[
        (df['Company'] == company) &
        (df['Year'] == 2025)
    ]['Net Income Growth (%)'].iloc[0]

    print(
        f"{company}'s net income changed by "
        f"{net_income_growth:.2f}% from 2024 to 2025."
    )

Microsoft's net income changed by 15.54% from 2024 to 2025.
Apple's net income changed by 19.50% from 2024 to 2025.
Tesla's net income changed by -46.11% from 2024 to 2025.

In [32]:
#creating Query 4 and adding to responses: Net income change.
for company in ['Microsoft', 'Apple', 'Tesla']:
    net_income_growth = df[
        (df['Company'] == company) &
        (df['Year'] == 2025)
    ]['Net Income Growth (%)'].iloc[0]

    responses[
        f"How did {company}'s net income change from 2024 to 2025?"
    ] = (
        f"{company}'s net income changed by "
        f"{net_income_growth:.2f}% from 2024 to 2025."
    )

In [33]:
responses

{"What was Apple's revenue in 2025?": "Apple's total revenue in 2025 was 416,161.",
 "What was Microsoft's revenue in 2025?": "Microsoft's total revenue in 2025 was 281,724.",
 "What was Tesla's revenue in 2025?": "Tesla's total revenue in 2025 was 97,690.",
 "What was Microsoft's net income in 2025?": "Microsoft's net income in 2025 was 101,832.",
 "What was Apple's net income in 2025?": "Apple's net income in 2025 was 112,010.",
 "What was Tesla's net income in 2025?": "Tesla's net income in 2025 was 3,855.",
 "How did Microsoft's revenue change from 2024 to 2025?": "Microsoft's revenue changed by 14.93% from 2024 to 2025.",
 "How did Apple's revenue change from 2024 to 2025?": "Apple's revenue changed by 6.43% from 2024 to 2025.",
 "How did Tesla's revenue change from 2024 to 2025?": "Tesla's revenue changed by -2.93% from 2024 to 2025.",
 "How did Microsoft's net income change from 2024 to 2025?": "Microsoft's net income changed by 15.54% from 2024 to 2025.",
 "How did Apple's net income change from 2024 to 2025?": "Apple's net income changed by 19.50% from 2024 to 2025.",
 "How did Tesla's net income change from 2024 to 2025?": "Tesla's net income changed by -46.11% from 2024 to 2025."}

In [35]:
#Calculate the average revenue
average_revenue = df.groupby('Company')['Total Revenue'].mean()

average_revenue

Company
Apple        396827.000000
Microsoft    246253.666667
Tesla         96430.000000
Name: Total Revenue, dtype: float64

In [36]:
#creating Query 5 and adding to responses: Average Revenue.
for company in ['Microsoft', 'Apple', 'Tesla']:
    avg_revenue = df[
        df['Company'] == company
    ]['Total Revenue'].mean()

    responses[
        f"What was the average revenue for {company} from 2023 to 2025?"
    ] = (
        f"{company}'s average revenue from 2023 to 2025 "
        f"was {avg_revenue:,.2f}."
    )

In [37]:
responses #checking all responses and queries

{"What was Apple's revenue in 2025?": "Apple's total revenue in 2025 was 416,161.",
 "What was Microsoft's revenue in 2025?": "Microsoft's total revenue in 2025 was 281,724.",
 "What was Tesla's revenue in 2025?": "Tesla's total revenue in 2025 was 97,690.",
 "What was Microsoft's net income in 2025?": "Microsoft's net income in 2025 was 101,832.",
 "What was Apple's net income in 2025?": "Apple's net income in 2025 was 112,010.",
 "What was Tesla's net income in 2025?": "Tesla's net income in 2025 was 3,855.",
 "How did Microsoft's revenue change from 2024 to 2025?": "Microsoft's revenue changed by 14.93% from 2024 to 2025.",
 "How did Apple's revenue change from 2024 to 2025?": "Apple's revenue changed by 6.43% from 2024 to 2025.",
 "How did Tesla's revenue change from 2024 to 2025?": "Tesla's revenue changed by -2.93% from 2024 to 2025.",
 "How did Microsoft's net income change from 2024 to 2025?": "Microsoft's net income changed by 15.54% from 2024 to 2025.",
 "How did Apple's net income change from 2024 to 2025?": "Apple's net income changed by 19.50% from 2024 to 2025.",
 "How did Tesla's net income change from 2024 to 2025?": "Tesla's net income changed by -46.11% from 2024 to 2025.",
 'What was the average revenue for Microsoft from 2023 to 2025?': "Microsoft's average revenue from 2023 to 2025 was 246,253.67.",
 'What was the average revenue for Apple from 2023 to 2025?': "Apple's average revenue from 2023 to 2025 was 396,827.00.",
 'What was the average revenue for Tesla from 2023 to 2025?': "Tesla's average revenue from 2023 to 2025 was 96,430.00."}

## Step 3: Building chatbot logic

In [38]:
#creating a function for the chatbot to check queries
def simple_chatbot(user_query):
    if user_query in responses:
        return responses[user_query]
    else:
        return "Sorry, I can only provide information on predefined queries."

In [39]:
# Testing a query
simple_chatbot("What was Apple's revenue in 2025?")

"Apple's total revenue in 2025 was 416,161."

In [40]:
# Testing an unsupported query
simple_chatbot("What is Apple's stock price?")

'Sorry, I can only provide information on predefined queries.'

## Efficiency
We can use if else statements but the approach we have now is more efficient. if/else statements would look like this:

def simple_chatbot(user_query):
    
    if user_query == "What was Apple's revenue in 2025?":
        return responses[user_query]
    
    elif user_query == "What was Microsoft's revenue in 2025?":
        return responses[user_query]
    
    elif user_query == "What was Tesla's revenue in 2025?":
        return responses[user_query]
    
    elif user_query == "What was Apple's net income in 2025?":
        return responses[user_query]
    
    elif user_query == "What was Microsoft's net income in 2025?":
        return responses[user_query]
    
    elif user_query == "What was Tesla's net income in 2025?":
        return responses[user_query]
    
    else:
        return "Sorry, I can only provide information on predefined queries."

In [42]:
# Prompting user for input
user_query = input("Ask me a financial question: ")

response = simple_chatbot(user_query)

print(response)

Ask me a financial question:  What was Apple's revenue in 2025?

Apple's total revenue in 2025 was 416,161.

## Query structure
Because we're using exact matching, the question has to match the predefined query exactly.
So we can make the questions clickable or selectable